#!/usr/bin/env bash

# Manage EasyPHP dev server.

#-------------
# Variables
#-------------

exe_path="/d/Feri_dolgai/Programs/srv/EasyPHP-DevServer-13.1VC11.exe"
vhost_url="http://127.0.0.1/modules/virtualhostsmanager/virtualhostsmanager_update.php"
usage="Usage: vhost {start|stop|restart|status|up|down}"
srv_pid=""
vhost_data=()
vhost_nr=vhost_data[0]
vhost_name=vhost_data[1]
vhost_hash=vhost_data[2]
#-------------
# Functions
#-------------

get_pid() {
    srv_pid=$(ps aux | grep '[E]asyPHP' | awk '{print $1}')
}

get_vhost_data() {
    local get_vhost="$1"
    local vhost_nr=vhost[0]
    local vhost_name=vhost[1]
    local data_rest=$(curl -s -G -d "to=status_host" $vhost_url)
    data_rest=${data_rest#*!}

    while [[ "$data_rest" != "" ]]; do

        vhost=( ${data_rest%%!*} )
        if [[ "$get_vhost" ]]; then
            if [[ "$get_vhost" == "${!vhost_name}" || "$get_vhost" == "${!vhost_nr}" ]]; then
                vhost_data=${vhost[@]}
                return
            fi
        else
            echo ${vhost[@]}
        fi
        data_rest=${data_rest#*!}
    done

    if [[ "$get_vhost" && "$vhost_data" == "" ]]; then
        echo "No vhost found!"
        exit 1
    fi
}

get_pid

# Use cases
case "$1" in
        st|start)
            if [[ "$srv_pid" == "" ]]; then
                $exe_path&
                echo "Dev server ready!"
            else
                echo "Already running!"
            fi
            ;;

        k|kill|stop)
            if [[ "$srv_pid" != "" ]]; then
                kill "$srv_pid"
                echo "Dev server shut down!"
            else
                echo "No server to stop!"
            fi
            ;;

        rs|rst|restart)
            if [[ "$srv_pid" != "" ]]; then
                kill "$srv_pid"
                $exe_path&
                get_pid
                echo "$srv_pid"
                echo "Dev server reseted!"
            else
                echo "No server to restart!"
            fi
            ;;

        s|stat|status)
            # status vhost
            if [[ "$srv_pid" == "" ]]; then
                echo "No server!"
            else
                echo "Server running! Virtual Hosts:"
                echo "------------------------------"
                get_vhost_data
            fi
            ;;

        u|up)
            # activate vhost
            #     GET
            #     to="onoff_host"
            #       hash="off" #status
            #       servername="vhst-server-name"
            #       num_virtualhost="vhost-number"

            if [[ "$srv_pid" == "" ]]; then
                echo "No server!"
                exit 0;
            fi

            get_vhost_data "$2"
            echo "VHOST= ${vhost_data[@]}"

            # # "$vhost_path" to=
            onoff_host&
            hash=on&
            servername=post.dev&
            num_virtualhost=0
            # "$vhost_path" to=onoff_host&
            hash=off&
            servername=www.nagyvaradhotel.ro&
            num_virtualhost=1
            # "$vhost_path" to=onoff_host&hash=on&servername=dev.nagyvaradhotel.ro&num_virtualhost=2
            # "$vhost_path" to=onoff_host&hash=off&servername=posticumhost.ro&num_virtualhost=3


            echo "VirtualHost ${!vhost_name} up!"
            ;;
        d|down)
            # deactivate vhost
            #     GET
            #     to="onoff_host"
            #       hash="on" #status
            #       servername="vhst-server-name"
            #       num_virtualhost="vhost-number"
            if [[ "$srv_pid" == "" ]]; then
                echo "No server!"
                exit 0;
            fi

            get_vhost_data "$2"
            echo "VHOST= ${vhost_data[@]}"

            echo "VirtualHost ${!vhost_name} down!"
            ;;
        a|add)
            # add vhost
            #     POST
            #     to="add_vhost_2"
            #     lang="en"
            #       vhost_name="link-to-vhost" max 65
            #       vhost_link="path-to-vhost" max 80
            if [[ "$srv_pid" == "" ]]; then
                echo "No server!"
                exit 0;
            fi


            echo "VirtualHost ${!vhost_name} added!"
            ;;
        del|rm|remove|delete)
            # delete vhost
            #     GET
            #     to="del_virtualhost"
            #       num_virtualhost="virtualhost-number"
            if [[ "$srv_pid" == "" ]]; then
                echo "No server!"
                exit 0;
            fi


            echo "VirtualHost ${!vhost_name} removed!"
            ;;

        *)
            echo "$usage"
            exit 1
esac
